disable_ray: true
max_tokens: 256
models:
- meta-llama/Llama-2-7b-hf
num_gpus: 2
num_tensor_parallel_workers:
- 2
output_dir: vidur/profiling/fth_profiling_outputs/mlp/2025-02-21_10-53-09
profile_method: record_function
